### ISSUE TITLE
feat: Add responsive footer 

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/events#12]
Include our Social links:
Facebook: https://web.facebook.com/SurPathHub
LinkedIn: https://www.linkedin.com/company/surpathhub/
Twitter: https://twitter.com/hashtag/SurPathHub?src=hashtag_click
YouTube: https://www.youtube.com/channel/UCjA75ni_WO_AoyWsLxnnwjA

The footer should look like this: https://www.youtube.com/watch?v=zdA3qZNH1vc
![image](https://user-images.githubusercontent.com/73097560/124106804-2a540b80-da97-11eb-8667-391a6166534b.png)

**Comment by Beatrix-droid** [comment]
can i try working on this?

**Comment by vinzvinci** [comment]
Yeah sure @Beatrix-droid.

**Comment by Beatrix-droid** [comment]
Cool, will have a crack at it tomorrow and aim to have it done by the evening

**Comment by vinzvinci** [comment]
Any updates on this issue?

**Comment by Beatrix-droid** [comment]
hi, apologies for taking so long, some other code i was fixing form another repo ended up taking longer than usual so everything ended up being pushed to a day later. I am working  on this right now actually :)

**Comment by vinzvinci** [comment]
No worries. I'm just checking if u still up for this.
