### ISSUE TITLE
Color of "100"

### ISSUE THREAD

**Issue by rynrsts** [SurPathHub/events#21]
**Describe the bug**
The word "100" is just color red for a mobile phone. And, it is not blinking, or what, compared to a laptop. This is also true when using device emulation in WebDev Tools.

**To Reproduce**
1. Use a mobile device.
2. Go to the main page.

**Expected behavior**
I really do not know what and how it should be. But it looks different in a mobile phone, compared to a laptop.

**Screenshots**
Mobile phone:
![image](https://user-images.githubusercontent.com/84888155/124600176-0890c500-de99-11eb-9771-c4284ff7d4e4.png)
Laptop:
![image](https://user-images.githubusercontent.com/84888155/124600970-e3508680-de99-11eb-8339-775cf6ea59a5.png)

**Working Environment**

Operating System (eg. Linux): Android for mobile device, and Windows for laptop.

Browser (eg. Chrome): Chrome for mobile device, and MS Edge for laptop.

Device (eg. Laptop or Phone): The issue is in mobile phone.

**Additional context**
I think that the red border is eating the space inside the "100" when in a mobile phone.

Sorry, but I cannot fix this issue right now, or within this week.

**Comment by vinzvinci** [comment]
Thank you for raising this issue, other dev may take this issue.

**Comment by Prod-IP** [comment]
Hello @vinzvinci please assign this to me

**Comment by vinzvinci** [comment]
Done, please share screenshots of what you did to the website or enable the GitHub pages in: <a href="https://github.com/Prodip-Kumar-Paul/events/pages">https://github.com/Prodip-Kumar-Paul/events/pages</a> @Prodip-Kumar-Paul. And we will be able to see the results here: [Prodip-Kumar-Paul.github.io/events](https://prodip-kumar-paul.github.io/events). Thank you

**Comment by Prod-IP** [comment]
I have enable github pages , @vinzvinci  now you can see it [here](https://prodip-kumar-paul.github.io/events/)
