### ISSUE TITLE
#100DaysOfCode - Draw an Octocat Challenge 

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/events#27]
# #MyOctocat Challenge
### Prize: `Octocat figurine`
- We will only choose 1 winner for this challenge
<hr />

### How to enter this contest?

- Only people who registered on this event can join (The registration was ended)
- Draw an Octocat 
  - (**Start:** September 1, 2021 - **Deadline:** September 15, 2021 - 11:59 PM)

### Posting date and time on Twitter:
  - **(Start: September 15, 2021 - 1:00PM)**
    - Post your drawing on this date so no one will copy your idea.
  - **(End: September 16, 2021 - 12:00 AM)**
### Rules
- Octocats created by http://myoctocat.com generator is not eligible to win.
- No digital drawing.
- You need to put your signature on your drawing.
- Only residents from the Philippines can enter this contest

### Judging criteria
- Originality 
- Adherence to Theme
- Best draw wins!

### You need to post it on Twitter:
- Picture your drawing, upload, and tweet it to @GitHubEducation #SurPathHub #MyOctocat #GitHubPhilippines
- Please share the tweet link below 

Sample post: https://twitter.com/hashtag/MyOctocat?src=hashtag_click
`Don't forget these in your post: @GitHubEducation #SurPathHub #MyOctocat #GitHubPhilippines`
<hr />

### Way of shipping for the winner:
- The Octocat figurine is already delivered in the Philippines, we will ask the winner for the shipping address.
- **Everything is paid by GitHub**, you don't need to pay anything if you receive your item!

**Comment by nikxherrera** [comment]
**Tweet Link :** 

https://twitter.com/nikxherrera/status/1438091306069159939

**Comment by igbaras** [comment]
Tweet Link:
[https://twitter.com/christianigbar1/status/1438111320243531777](url)

**Comment by vinzvinci** [comment]
# The winner of the #MyOctocat challenge 🥳 

Congrats @Tiansing 🎉 

![image](https://user-images.githubusercontent.com/73097560/133533461-751f0d31-f497-4651-bab1-d8811ee81b41.png)

Expect your reward this Saturday :octocat:

**Comment by igbaras** [comment]
Thank you @vinzvinci
