### ISSUE TITLE
Feat: Add the student developer pack

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/events#31]
We need to add this section of the student developer pack to the website.

**To Do:**
- Responsive section
- One button just like the header `(center the button)`
- This picture:
![studentdeveloperpack](https://user-images.githubusercontent.com/73097560/125257999-838e2b80-e330-11eb-9afd-ccd2cd8dae08.png)

**Comment by igbaras** [comment]
Master, You can now close this issue
