### ISSUE TITLE
Discord image

### ISSUE THREAD

**Issue by rynrsts** [SurPathHub/events#35]
The Discord image in the website has fake transparency.

![image](https://user-images.githubusercontent.com/84888155/126290868-59d555aa-59ef-401e-b9b2-ecd5ec5e22fe.png)

**Comment by rynrsts** [comment]
If no one is doing this, I could edit the image and replace it with a transparent one.

**Comment by vinzvinci** [comment]
Hey, yeah please do it. Thank you!
