### ISSUE TITLE
Make the dinosaur animation responsive

### ISSUE THREAD

**Issue by igbaras** [SurPathHub/events#5]
Modify the dinosaur animation by adding media query in it. 
![image](https://user-images.githubusercontent.com/59194525/123932103-b09f1d80-d9c3-11eb-9377-c48097550163.png)

**Comment by godwin-morwin** [comment]
hi , i will like to work on this issue

**Comment by vinzvinci** [comment]
Hi @Godwindaniel10, I assigned this issue to you.

**Comment by godwin-morwin** [comment]
aiit, thanks

**Comment by vinzvinci** [comment]
Any update on this issue?

**Comment by godwin-morwin** [comment]
Planned on working on the issue today

**Comment by vinzvinci** [comment]
Okay, waiting for it @Godwindaniel10

**Comment by godwin-morwin** [comment]
aiit

**Comment by vinzvinci** [comment]
Tell me when you're done @Godwindaniel10

**Comment by godwin-morwin** [comment]
@vinzvinci , i have submitted a PR
