### ISSUE TITLE
feat: Add responsive navbar 

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/events#7]
logo of SurPath on the left, then on the right side: **Home**, **Challenges*, **FAQs**, **Socials**

**Comment by godwin-morwin** [comment]
i can work on this issue as well

**Comment by vinzvinci** [comment]
Sure @Godwindaniel10, please make the navbar background transparent. We also have #9, feel free to fix it if you can.

**Comment by vinzvinci** [comment]
I will do this issue for the better, sorry.

**Comment by godwin-morwin** [comment]
was there a problem with the one i did?

if yes , what was the problem ?

**Comment by vinzvinci** [comment]
The animation of FAQ just broke also the animation of buttons has removed. The navbar doesn't looks well

**Comment by godwin-morwin** [comment]
aiit

**Comment by igbaras** [comment]
> logo of SurPath on the left, then on the right side: **Home**, *_Challenges_, **FAQs**, **Socials**

I've already fixed this issue @vinzvinci
