### ISSUE TITLE
Website responsiveness is broken

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/events#9]
Desktop mode:
![image](https://user-images.githubusercontent.com/73097560/124091331-4c925d00-da88-11eb-861d-8e5f7c3f45b6.png)

Mobile:
![image](https://user-images.githubusercontent.com/73097560/124091618-9d09ba80-da88-11eb-8d32-794d04063525.png)

**Comment by vinzvinci** [comment]
Anyone who's interested can take this issue

**Comment by srisatya12** [comment]
Will try to work on this.

**Comment by vinzvinci** [comment]
Okay thanks

**Comment by ashwinexe** [comment]
I think I have fixed the issue. Can I create a PR?

**Comment by vinzvinci** [comment]
Sure @ashwinexe

**Comment by vinzvinci** [comment]
Hi @srisatya1197. I will open new issues, just wait.

**Comment by vinzvinci** [comment]
There are new open issues #10 #12 #13
